import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { inlineButton, inlineKeyboard, requireOwner } from "../toolkit/index.js";
import { Store } from "../store.js";

const composer = new Composer<Ctx>();
composer.callbackQuery("owner:orders", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireOwner(ctx))) return; const orders=(await new Store(ctx).orders()).filter((order)=>order.delivery_status==="awaiting_delivery"); if(!orders.length){await ctx.reply("لا توجد طلبات بانتظار التسليم.");return;} await ctx.reply("اختر طلباً لتسليمه.",{reply_markup:inlineKeyboard(orders.map((order)=>[inlineButton(`طلب ${order.id.slice(-6)}`,`deliver:${order.id}`)]))}); });
composer.on("callback_query:data", async (ctx, next) => { const data=ctx.callbackQuery.data; if(!data.startsWith("deliver:"))return next(); await ctx.answerCallbackQuery(); if(!(await requireOwner(ctx)))return; const order=await new Store(ctx).order(data.slice(8)); if(!order){await ctx.reply("لم يعد هذا الطلب متاحاً.");return;} if(order.payment_status!=="confirmed"){await ctx.reply("لا يمكن التسليم قبل تأكيد الدفع.");return;} if(order.delivery_status==="delivered"){await ctx.reply("تم تسليم هذا الطلب بالفعل.");return;} ctx.session={step:"delivery",orderId:order.id}; await ctx.reply("أرسل رسالة التسليم أو ملف المنتج الآن."); });
composer.on("message", async (ctx, next) => { if(ctx.session.step!=="delivery") return next(); if(!(await requireOwner(ctx)))return; const id=ctx.session.orderId; if(!id){ctx.session={};return;} const store=new Store(ctx); const order=await store.order(id); if(!order||order.payment_status!=="confirmed"){ctx.session={};await ctx.reply("لا يمكن التسليم قبل تأكيد الدفع.");return;} try { if(ctx.message.text) await ctx.api.sendMessage(order.buyer_chat_id, `تم تسليم طلبك.\n\n${ctx.message.text}`); else await ctx.api.copyMessage(order.buyer_chat_id, ctx.chat.id, ctx.message.message_id); await store.deliver(id,ctx.message.text); ctx.session={}; await ctx.reply("تم إرسال الطلب للمشتري وتحديث حالته."); } catch { await ctx.reply("تعذر إرسال التسليم للمشتري. تأكد أنه لم يحظر البوت ثم حاول مرة أخرى."); } });
export default composer;
